import os
import sys
import pytest

from pathlib import Path

# If the main module is translated to Python, import it; otherwise, use a stub/mock.
try:
    import src.babel_plugin_functional_hmr as plugin
    PLUGIN_AVAILABLE = True
except ImportError:
    PLUGIN_AVAILABLE = False
    plugin = None

# Utilities to simulate JS-style fixture file handling
def _fixture_path(fname):
    return Path(__file__).parent.parent.parent / "lib" / "__fixtures__" / fname

def _read(fname):
    with open(_fixture_path(fname), encoding="utf-8") as f:
        return f.read()

def l(string):
    """Split lines, filter specific line(s), mimic ESLint filter in JS test."""
    return [line for line in string.strip().split('\n') if line != '/* eslint-disable */']

# Simulated transform function, to be replaced with actual plugin Python port
def transform_js_code(source_code):
    # Placeholder: You must implement the actual transformation logic in src/babel_plugin_functional_hmr.py
    # For test completeness, we'll just echo the input.
    # In real use, this should run the plugin's Python transformation and return resulting code as string.
    return source_code

@pytest.mark.parametrize("fixture,snapshot_name", [
    ('class-already', 'already a class, should not transform anything 1'),
    ('export-default-param', 'function, should transform 1'),
    ('declared-as-const', 'function as const, should transform 1'),
    ('simplefunction', 'simple function, should not change 1'),
    ('simplefunction-multiple-param', 'simple function with more than on 1 parameter, should not change 1'),
    ('non-jsx-body', 'functional component like function with non-jsx body, should not change 1'),
    ('multiple-components', 'multiple components, should change 1'),
    ('nondefault-components', 'non default components, should change 1'),
    ('declared-as-const-no-param', 'no parameters, should change 1'),
    ('nontoplevel', 'non toplevel, should not change 1'),
    ('embedded-return', 'embedded return, should change 1'),
    ('embedded-return-arguments', 'embedded return with argument, should change 1'),
    ('embedded-return-extra-statements', 'embedded return with argument, should change 2'),
    ('destructure', 'const with destructure in param, should change 1'),
    ('class-and-function', 'simple function with destructed param 1'),
    ('wrapped-in-hoc', 'component wrapped in hoc 1'),
])
def test_plugin_fixture_parity(fixture, snapshot_name, request):
    """Ported from Jest test structure. Asserts output of transform matches the expected snapshot."""
    source = _read(f"{fixture}.js")
    code = transform_js_code(source)
    result_lines = l(code)
    expected_snapshot = SNAPSHOTS[snapshot_name]
    assert result_lines == expected_snapshot

# Snapshots from Jest __snapshots__/plugin.test.js.snap -- translated to Python lists
SNAPSHOTS = {
    "already a class, should not transform anything 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "export default class Button extends Component {",
        "    render() {",
        "        return <TouchableNativeFeedback onPress={this.props.onPress}>",
        "                <Text style={{ color: 'green' }}>",
        "                    {this.props.title}",
        "                </Text>",
        "            </TouchableNativeFeedback>;",
        "    }",
        "}",
    ],
    "function, should transform 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Comp extends _react.Component {",
        "    render() {",
        "        let { children, onPress } = this.props;",
        "        return (<TouchableNativeFeedback onPress={onPress}>",
        "        <Text style={{ color: 'blue' }}>",
        "            {children}",
        "        </Text>",
        "    </TouchableNativeFeedback>);",
        "    }",
        "",
        "}",
        "",
        "const Comp = wrapComponent('Comp', __Comp);",
        "export default Comp;",
    ],
    "function as const, should transform 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { children, onPress } = this.props;",
        "        return (<TouchableNativeFeedback onPress={onPress}>",
        "        <Text style={{ color: 'blue' }}>",
        "            {children}",
        "        </Text>",
        "    </TouchableNativeFeedback>);",
        "    }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "simple function, should not change 1": [
        "export default (number => number * 2);",
    ],
    "simple function with more than on 1 parameter, should not change 1": [
        "export default ((number, multiplier) => number * multiplier);",
    ],
    "functional component like function with non-jsx body, should not change 1": [
        "export default (({ number }) => number * 2);",
    ],
    "multiple components, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { children, onPress } = this.props;",
        "        return (<TouchableNativeFeedback onPress={onPress}>",
        "        <Text style={{ color: 'blue' }}>",
        "            {children}",
        "        </Text>",
        "    </TouchableNativeFeedback>);",
        "    }",
        "",
        "}",
        "",
        "export const Button = wrapComponent('Button', __Button);",
        "",
        "class __Box extends _react.Component {",
        "    render() {",
        "        let { children, onPress } = this.props;",
        "        return (<TouchableNativeFeedback onPress={onPress}>",
        "        {children}",
        "    </TouchableNativeFeedback>);",
        "    }",
        "",
        "}",
        "",
        "export const Box = wrapComponent('Box', __Box);",
    ],
    "non default components, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { children, onPress } = this.props;",
        "        return (<TouchableNativeFeedback onPress={onPress}>",
        "        <Text style={{ color: 'blue' }}>",
        "            {children}",
        "        </Text>",
        "    </TouchableNativeFeedback>);",
        "    }",
        "",
        "}",
        "",
        "export const Button = wrapComponent('Button', __Button);",
    ],
    "no parameters, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "  const t = _reactTransform({",
        "    components: {",
        "      [id]: {",
        "        displayName: id",
        "      }",
        "    },",
        "    locals: [module],",
        "    imports: [_react],",
        "    filename: '%%FILENAME%%'",
        "  });",
        "",
        "  return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "  render() {",
        "    return (<Text style={{ color: 'blue' }}>Test</Text>);",
        "  }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "non toplevel, should not change 1": [
        "storiesOf('Welcome', module).add('to Storybook', () => <Welcome showApp={linkTo('Button')} />);",
    ],
    "embedded return, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        return (<Text style={{ color: 'blue' }}>Test</Text>);",
        "    }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "embedded return with argument, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { title } = this.props;",
        "        return (<Text style={{ color: 'blue' }}>",
        "            {title}",
        "        </Text>);",
        "    }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "embedded return with argument, should change 2": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { title } = this.props;",
        "",
        "        const string = title.toUpperCase();",
        "        const sum = 1 + 2;",
        "        return (<Text style={{ color: 'blue' }}>",
        "            {string}",
        "        </Text>);",
        "    }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "const with destructure in param, should change 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Button extends _react.Component {",
        "    render() {",
        "        let { children, layout: { width, height } } = this.props;",
        "        return (<Text style={{ color: 'blue' }} width={width} height={height}>",
        "        {children}",
        "    </Text>);",
        "    }",
        "",
        "}",
        "",
        "const Button = wrapComponent('Button', __Button);",
        "",
        "",
        "export default Button;",
    ],
    "simple function with destructed param 1": [
        "import { TouchableNativeFeedback, Text } from 'react-native';",
        "import React, { Component, PropTypes } from 'react';",
        "",
        "const renderItem = ({ item: { date } }) => <View>{date}</View>;",
        "",
        "export default class Button extends Component {",
        "    render() {",
        "        return <TouchableNativeFeedback onPress={this.props.onPress}>",
        "                <Text style={{ color: 'green' }}>",
        "                    {this.props.title}",
        "                </Text>",
        "            </TouchableNativeFeedback>;",
        "    }",
        "}",
    ],
    "component wrapped in hoc 1": [
        "import { Text } from 'react-native';",
        "import React from 'react';",
        "",
        "const withNumber = number => {",
        "    return BaseComponent => {",
        "        return props => <BaseComponent {...props} number={number} />;",
        "    };",
        "};",
        "",
        "import _react from 'react';",
        "import _reactTransform from 'react-transform-hmr';",
        "",
        "function wrapComponent(id, Component) {",
        "    const t = _reactTransform({",
        "        components: {",
        "            [id]: {",
        "                displayName: id",
        "            }",
        "        },",
        "        locals: [module],",
        "        imports: [_react],",
        "        filename: '%%FILENAME%%'",
        "    });",
        "",
        "    return t(Component, id);",
        "}",
        "",
        "class __Test extends _react.Component {",
        "    render() {",
        "        let { number } = this.props;",
        "        return (<Text>",
        "            Test {number}",
        "        </Text>);",
        "    }",
        "",
        "}",
        "",
        "const Test = wrapComponent('Test', __Test);",
        "",
        "",
        "export default withNumber(3)(Test);",
    ]
}