plugins {
    id 'java'
    id 'jacoco'
}

group 'net.yacy.grid'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.2'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
            // Exclude all unbuildable code
            include 'net/yacy/grid/coverage/DemoCoverage.java'
            exclude 'net/yacy/grid/crawler/**'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
            include 'net/yacy/grid/coverage/DemoCoverageTest.java'
        }
    }
}

// Fix for duplicate log4j.properties resources error during processResources
tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}