import pytest
from src.is_number import is_number
import math
import random
import datetime

def test_is_a_number():
    fixtures = [
        0xff,
        5e3,
        0,
        0.1,
        -0.1,
        -1.1,
        37,
        3.14,
        1,
        1.1,
        10,
        10.1,
        100,
        -100,
        '0.1',
        '-0.1',
        '-1.1',
        '0',
        '012',
        '0xff',
        '1',
        '1.1',
        '10',
        '10.10',
        '100',
        '5e3',
        '   56\r\n  ',
        math.log(2),
        int('012'),
        float('012'),
        abs(1),
        math.acos(1),
        math.asin(1),
        math.atan(1),
        math.atan2(1, 2),
        math.ceil(1),
        math.cos(1),
        math.e,
        math.exp(1),
        math.floor(1),
        math.log(10),
        math.log(2),
        math.log(1),
        math.log10(10),
        math.log2(2),
        max(1, 2),
        min(1, 2),
        math.pi,
        pow(1, 2),
        pow(5, 5),
        random.random(),
        round(1),
        math.sin(1),
        math.sqrt(1),
        math.sqrt(0.5),
        math.sqrt(2),
        math.tan(1),
        float("1.79e308"),
        float("5e-324"),
        '0.0',
        '0x0',
        '0e+5',
        '000',
        '0.0e-5',
        '0.0E5',
        float('0'),
        1,
        3.14,
        37,
        5,
        float([]) if [] else 0,  # [] is falsy, so float(0)
        float(False),
        math.log(2),
        float(True),
        float(None) if None else 0,
        datetime.datetime.now().timestamp(),
    ]
    for idx, num in enumerate(fixtures):
        assert is_number(num), f'expected "{str(num)}" to be a number'

def test_is_not_a_number():
    fixtures = [
        '   ',
        '\r\n\t',
        '',
        '',
        '3a',
        'abc',
        'false',
        'null',
        'true',
        'undefined',
        float('nan'),
        float('inf'),
        [1, 2, 4],
        float('inf'),
        math.sin,
        float('nan'),
        None,
        {'a': 1},
        {},
        re.compile('foo'),
        [1, 2, 3],
        [1],
        [],
        True,
        False,
        (lambda: None),
        (lambda: 1),
        float('inf'),
        -float('inf'),
        math.sin,
        float('nan'),
        datetime.datetime.now(),
        None,
        None,
        {},
    ]
    import re
    for num in fixtures:
        assert not is_number(num), f'expected "{str(num)}" to not be a number'