from src.jsonstream import jsonstream

def test_roundtrip_parse_and_stringify_with_alternative_data():
    input_data = [
        {'a': 5, 'b': 7},
        {'a': 0, 'b': 14}
    ]
    stringify = jsonstream.stringify()
    parse = jsonstream.parse('*')
    output = []
    # Simulate piping: for each chunk generated by stringify, push to parser
    for obj in parse.parse_stream(stringify.write_items(input_data)):
        output.append(obj)
    assert output == input_data